[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npx prisma migrate deploy"]

[start]
cmd = "cd backend && node src/app.js"